# Dockerfile for Spring Boot Admin Server
FROM openjdk:11-jre-slim
COPY ./spring-admin-server/target/spring-boot-admin-0.0.1-SNAPSHOT.jar /usr/app/
WORKDIR /usr/app
ENTRYPOINT ["java", "-jar", "admin-server.jar"]
EXPOSE 8084
