version: '3.8'
services:
  user-service:
    build: ./UserService
    ports:
      - "8081:8081"
    environment:
      - EUREKA_SERVER=http://service-registry:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/FRD
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=anujena
    depends_on:
      - service-registry
#      - sqlserver

  product-service:
    build: ./ProductService
    ports:
      - "8082:8082"
    environment:
      - EUREKA_SERVER=http://service-registry:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/FRD1
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=anujena
    depends_on:
      - service-registry
#      - sqlserver

  order-service:
    build: ./OrderService
    ports:
      - "8083:8083"
    environment:
      - EUREKA_SERVER=http://service-registry:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/FRD2
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=anujena
    depends_on:
      - service-registry
#      - sqlserver

  api-gateway:
    build: ./ApiGateway
    ports:
      - "8084:8084"
    environment:
      - EUREKA_SERVER=http://service-registry:8761/eureka/
    depends_on:
      - service-registry

  service-registry:
    build: ./ServiceRegistry
    ports:
      - "8761:8761"

  config-server:
    build: ./ConfigServer
    ports:
      - "8085:8085"

  admin-server:
    build: ./spring-admin-server
    ports:
      - "8084:8084"
    depends_on:
      - service-registry

#  sqlserver:
#    image: mcr.microsoft.com/mssql/server:2019-latest
#    environment:
#      SA_PASSWORD: "anujena"
#      ACCEPT_EULA: "Y"
#    ports:
#      - "3306:3306"
#    volumes:
#      - sqlserverdata:/var/opt/mssql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

#volumes:
#  sqlserverdata:
#     driver: local
