version: '4.22'
services:
  user-service:
    build: ./UserService/UserService
    ports:
      - "8081:8081"
    environment:
      - EUREKA_SERVER=http://service-registry:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/FRD
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=anujena
    depends_on:
      - service-registry
      - mysql-db

  product-service:
    build: ./ProductService/ProductService
    ports:
      - "8082:8082"
    environment:
      - EUREKA_SERVER=http://service-registry:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/FRD1
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=anujena
    depends_on:
      - service-registry
      - mysql-db

  order-service:
    build: ./OrderService/OrderService
    ports:
      - "8083:8083"
    environment:
      - EUREKA_SERVER=http://service-registry:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/FRD2
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=anujena
    depends_on:
      - service-registry
      - mysql-db

  api-gateway:
    build: ./ApiGateway/ApiGateway
    ports:
      - "8084:8084"
    environment:
      - EUREKA_SERVER=http://service-registry:8761/eureka/
    depends_on:
      - service-registry

  service-registry:
    build: ./ServiceRegistry/ServiceRegistry
    ports:
      - "8761:8761"

  config-server:
    build: ./ConfigServer/ConfigServer
    ports:
      - "8085:8085"

  # admin-server:
  #   build: ./spring-admin-server
  #   ports:
  #     - "8084:8084"
  #   depends_on:
  #     - service-registry

  mysql-db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: anujena
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

volumes:
  mysql-data:
