version: '3.8'
services:
  eureka-server:
    image: eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
#  api-gateway:
#    image: api-gateway
#    build:
#      context: ./api-gateway
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - eureka-server
#  user-management:
#    image: user-management
#    build:
#      context: ./user-management
#      dockerfile: Dockerfile
#    ports:
#      - "8081:8081"
#    depends_on:
#      - eureka-server
#  product-management:
#    image: product-management
#    build:
#      context: ./product-management
#      dockerfile: Dockerfile
#    ports:
#      - "8082:8082"
#    depends_on:
#      - eureka-server
#  order-processing:
#    image: order-processing
#    build:
#      context: ./order-processing
#      dockerfile: Dockerfile
#    ports:
#      - "8083:8083"
#    depends_on:
#      - eureka-server
#  redis:
#    image: "redis:alpine"
#    ports:
#      - "6379:6379"
#  kafka:
#    image: wurstmeister/kafka
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#    depends_on:
#      - zookeeper
#  zookeeper:
#    image: wurstmeister/zookeeper
#    ports:
#      - "2181:2181"